name: 🐞 Bug report of Netology rules
description: Шаблон - "Баг репорт" для использования в Issues GitHub, по правилам Нетологии.
title: "[BUG]: <title>"  
labels: [Bug]

body:
- type: input
  id: title
  attributes:
    label:  Название
    description: |
        последовательный ответ на три вопроса:
        ЧТО не так работает? ГДЕ не работает (в каком месте продукта)?  КОГДА данная проблема проявляется?
    placeholder:  "Что, где, когда."
  validations:
    required: true
- type: textarea
  id: bug_description
  attributes:
    label:  Описание
    description: "подробное описание возникшей ошибки и/или мнение, что могло повлиять на её возникновение"
    value: " ... "
    render: markdown
  validations:
    required: true
- type: input
  id: bug_expected
  attributes:
    label:  Ожидаемый результат
    description: "ожидаемое поведение проверяемого объекта"
    placeholder:  " ... "
  validations:
    required: true
- type: input
  id: bug_actual
  attributes:
    label:  Фактический результат
    description: "фактическое поведение проверяемого объекта"
    placeholder:  " ... "
  validations:
    required: true
- type: textarea
  id: bug_list
  attributes:
    label: Шаги воспроизведения
    description: "заполнить пошаговый список, для воспроизведения теста в котором выявилась ошибка"
    value: |
        1.  
        2.  
        3.  
        4.
        5.
        6.
        7.
    render:
  validations:
    required: true
- type: input
  id: bug_url
  attributes:
    label: Локация дефекта
    description: "Локация дефекта — это место тестируемого класса, где, на ваш взгляд, происходит дефект; можно указать просто на первую строчку объявления метода или вставить ссылку. Чтобы красиво сослаться на нужное место в коде, откройте файл класса на GitHub, нажмите на номер или номера соответствующей строки, удерживая Shift, и рядом слева нажмите на троеточие, в выпавшем меню нажмите Copy permalink. В буфер обмена скопируется прямая ссылка на строку этого коммита. Теперь вы её можете просто вставить в текст Issue, как в шаблоне: [Нетологя] (https://https://netology.ru/) без пробела."
    placeholder:  "ссылка на дефект"
  validations:
    required: true
- type: input
  id: bug_screen
  attributes:
    label: Скриншот ошибки
    description: "Скриншот - для загрузки изображений вы можете воспользоваться кнопкой, находящейся сразу под полем редактирования текста. Также возможна автозагрузка скриншотов прямо из буфера обмена через Ctrl+V с автовставкой в место нахождения курсора. Шаблон: ![image] (https://https://netology.ru/) без пробела."
    placeholder:  "ссылка на изображение"
  validations:
    required: true
- type: textarea
  id: bug_log
  attributes:
    label:  Логи сборки
    description: "Скопировать из приложения текст лога Ctrl+C и вставить Ctrl+V в этот блок."
    value: " вставить лог из приложения "
    render: markdown
  validations:
    required: false
- type: markdown
  attributes:
    value: |
          <br>
          ---
          <br>       
- type: textarea
  id: bug_surrounding
  attributes:
    label: ТЕСТОВОЕ ОКРУЖЕНИЕ
    description: "заполнить поле собственными параметрами или выбрать нужное в списках"
    value: |
      - ** OS **: Linux
    render:
  validations:
    required: false
    
- type: dropdown
  id: test_os
  attributes:
    label: "** OS **"
    options:
      - Windows 11
      - Windows 10
      - Windows 8
      - Windows 7
      - Windows Vista
      - Windows XP
      - macOS 14
      - macOS 13
      - macOS 12
      - macOS 11
      - macOS 10
      - Andoid 13
      - Andoid 12
      - Andoid 11
      - Andoid 10
      - Andoid 9
      - Andoid 8
      - Linux
      - Ubuntu
  validations:
    required: false
    
- type: dropdown
  id: test_programm
  attributes:
    label: "** Приложение **"
    options:
      - IntelliJ IDEA Community Edition
      - Edge
      - Chrome
      - Brave
  validations:
    required: false
    
- type: dropdown
  id: test_surrounding
  attributes:
    label: "** Среда тестирования **"
    options:
      - "Java: OpenJDK 11"
  validations:
    required: false
    
