name: 🐞 Bug report of Netology rules (заполнение в форме)
description: Шаблон - "Баг репорт" для использования в Issues GitHub, по правилам Нетологии, в формате .YML
title: "[BUG]: <вставить название>"
labels: [Bug]

body:
- type: markdown
  attributes:
    value:  |  
        <br><br>
        ---     
- type: input
  id: title
  attributes:
    label:  Название
    description: |
        последовательный ответ на три вопроса:
        ЧТО не так работает? ГДЕ не работает (в каком месте продукта)?  КОГДА данная проблема проявляется?
    placeholder:  "что, где, когда."
  validations:
    required: true
- type: textarea
  id: bug_description
  attributes:
    label:  Описание
    description: "описание возникшего дефекта и/или мнение, что могло привести к его возникновение"
    placeholder: "..."
    render: markdown
  validations:
    required: true
- type: markdown
  attributes:
    value: |
          <br><br>
          ---          
- type: textarea
  id: bug_steps
  attributes:
    label: Шаги воспроизведения
    description: "заполнить нумерованный список, для воспроизведения теста в котором выявился дефект"
    placeholder: |
        1.  
        2.  
        3.  
        ..
    render:
  validations:
    required: true
- type: input
  id: bug_expected
  attributes:
    label:  Ожидаемый результат
    description: "ожидаемое поведение проверяемого объекта"
    placeholder:  " ... "
  validations:
    required: true
- type: input
  id: bug_actual
  attributes:
    label:  Фактический результат
    description: "фактическое поведение проверяемого объекта"
    placeholder:  " ... "
  validations:
    required: true    
- type: textarea
  id: bug_url
  attributes:
    label: Локация дефекта
    description: "место тестируемого класса, где происходит дефект; можно указать первую строчку объявления метода или вставить ссылку. Чтобы красиво сослаться на нужное место в коде, нужно открыть файл класса на GitHub, нажать на номер (или номера) соответствующей строки удерживая Shift, рядом слева нажмать на троеточие, в выпавшем меню выбрать Copy permalink. В буфер обмена скопируется прямая ссылка на строку этого коммита. Теперь её можете просто вставить в текст Issue."
    placeholder:  "шаблон ссылки: [Название](url:)"
  validations:
    required: true
- type: textarea
  id: bug_screen
  attributes:
    label: Скриншот дефекта
    description:  "добавить ссылку на файл копии экрана с выявленным дефектом; можно указать ссылку на файл, либо сделать копию нужной части экрана (Win+Shift+S), затем вставить (Ctrl+V) в поле. GitHub закачает к себе копию экрана из буфера обмена"
    placeholder:  "шаблон ссылки: ![image](url:)"
  validations:
    required: true
- type: textarea
  id: bug_log
  attributes:
    label:  Лог сборки
    description: "скопировать текст лога сборки (Ctrl+C) и вставить (Ctrl+V) в этот блок"
    value:  |
        <details><summary>MVN CLEAN TEST</summary><p>
        
        ВСТАВИТЬ ВМЕСТО ЭТОГО ТЕКСТА
        
        </p></details> 
    render:
  validations:
    required: false
- type: markdown
  attributes:
    value: |
          <br><br>
          ---
          
- type: textarea
  id: bug_surrounding
  attributes:
    label: ТЕСТОВОЕ ОКРУЖЕНИЕ
    description: |
          заполнить поле собственными параметрами или выбрать нужное в списках.
    placeholder: |
       Пример:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    render:
  validations:
    required: false
    
- type: dropdown
  id: test_desktop_os
  attributes:
    label: "Настольные операционные системы"
    options:
      -  Windows 11
      -  Windows 10
      -  Windows 8
      -  Windows 7
      -  Windows Vista
      -  Windows XP
      -  macOS 14
      -  macOS 13
      -  macOS 12
      -  macOS 11
      -  macOS 10
      -  Linux
      -  Ubuntu
  validations:
    required: false
- type: dropdown
  id: test_mobile_os
  attributes:
    label: "Мобильные операционные системы"
    options:
      -  Andoid 13
      -  Andoid 12
      -  Andoid 11
      -  Andoid 10
      -  Andoid 9
      -  Andoid 8
      -  iOS 16
      -  iOS 15
      -  iOS 14
      -  iOS 13
      -  iOS 11
      -  iOS 10
      -  iOS 9
      -  iOS 8
      -  iOS 7
      -  iOS 6
      -  iOS 5
      -  Linux
      -  Ubuntu
  validations:
    required: false
    
- type: dropdown
  id: test_programm
  attributes:
    label: "Приложение"
    options:
      - "IDEA: IntelliJ IDEA Community Edition"
      - Browser   Edge
      - Browser  Chrome
      - Browser   Brave
  validations:
    required: false
    
- type: dropdown
  id: test_surrounding
  attributes:
    label: "Среда тестирования"
    options:
      - "Java:  OpenJDK 11"
  validations:
    required: false
    
